plugins {
    id "dev.architectury.loom-no-remap" version "1.17.493" apply false
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "com.gradleup.shadow" version "9.6.1" apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = createVersionString()
}

subprojects {
    apply plugin: "dev.architectury.loom-no-remap"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    base {
        archivesName = "${rootProject.archives_name}-${project.name}"
    }

    repositories {
        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
            content {
                includeGroup "maven.modrinth"
            }
        }
        maven { url = "https://maven.nucleoid.xyz/" }
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots" }
        maven { url = "https://maven.flashyreese.me/releases" }
        maven { url = "https://maven.flashyreese.me/snapshots" }
    }

    dependencies {
        minecraft "net.minecraft:minecraft:${rootProject.minecraft_version}"
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 25
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        repositories {
            maven {
                name = "FlashyReeseReleases"
                url = "https://maven.flashyreese.me/releases"
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_PASSWORD")
                }
            }
            maven {
                name = "FlashyReeseSnapshots"
                url = "https://maven.flashyreese.me/snapshots"
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_PASSWORD")
                }
            }
        }
    }
}

def createVersionString() {
    def builder = new StringBuilder()
    def isReleaseBuild = project.hasProperty("build.release")
    def buildId = System.getenv("GITHUB_RUN_NUMBER")

    if (isReleaseBuild) {
        builder.append(mod_version)
    } else {
        builder.append(mod_version.split("-")[0])
        builder.append("-snapshot")
    }

    builder.append("+mc").append(minecraft_version)

    if (!isReleaseBuild) {
        if (buildId != null) {
            builder.append("-build.").append(buildId)
        } else {
            builder.append("-local")
        }
    }

    return builder.toString()
}
