# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version=1.0.4
maven_group=me.flashyreese.mods
archives_name=commandaliases
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=26.3

# Platform dependencies
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3
neoforge_version=26.3.0.1-beta

# Fabric integrations
fabric_permissions_version=0.7.0
placeholder_api_version=3.2.0+26.3

# Common libraries
leveldb_version=0.12
mysql_version=26.7.0
jedis_version=8.0.1
jackson_version=2.22.2
jackson_annotations_version=2.22
javaaluator_version=3.0.6
