# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
	# check these on https://fabricmc.net/develop
    minecraft_version=26.1.2
	loader_version=0.19.2

# Mod Properties
	mod_version = 1.0.4
	maven_group = me.flashyreese.mods
	archives_base_name = commandaliases

# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
	fabric_version=0.146.0+26.1.2
